# typed: false
# frozen_string_literal: true

# Generated by scripts/update-editor.sh from the v0.1.35 release. Do not edit by hand.
cask "autodoc-editor" do
  version "0.1.35"

  on_arm do
    url "https://github.com/yongjohnlee80/autodoc/releases/download/v0.1.35/autodoc-editor-v0.1.35-darwin-arm64.tar.gz"
    sha256 "8c1b8555d7975812eeeb5dc54717e196bae0f1e6d1805d61899f7fe9172b0d75"
  end
  on_intel do
    url "https://github.com/yongjohnlee80/autodoc/releases/download/v0.1.35/autodoc-editor-v0.1.35-darwin-amd64.tar.gz"
    sha256 "b8ece067add8ccdb3cd6e9aa3d72934faab00bf7dff0427572e7dd4df2bbda36"
  end

  name "AutoDoc Editor"
  desc "Native Markdown editor and search UI for AutoDoc"
  homepage "https://github.com/yongjohnlee80/autodoc"
  depends_on :macos

  app "AutoDoc Editor.app"
  binary "#{appdir}/AutoDoc Editor.app/Contents/MacOS/autodoc-editor"
end
