# typed: false
# frozen_string_literal: true

# Generated by scripts/update-formula.sh from the v0.1.20 release. Do not edit by hand.
class Autodoc < Formula
  desc "Index, search and edit a tree of Markdown notes from a TUI or an RPC API"
  homepage "https://github.com/yongjohnlee80/autodoc"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/yongjohnlee80/autodoc/releases/download/v0.1.20/autodoc-v0.1.20-darwin-arm64.tar.gz"
      sha256 "b3dd33780e5ffee103ca75500fd699b1682db74a27be5357ff705c98e7b5852d"
    end
    on_intel do
      url "https://github.com/yongjohnlee80/autodoc/releases/download/v0.1.20/autodoc-v0.1.20-darwin-amd64.tar.gz"
      sha256 "d49f9f8a43504b75a566b45f98f21b2195e930b1956528d1e8b56eefc3dc8b7e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yongjohnlee80/autodoc/releases/download/v0.1.20/autodoc-v0.1.20-linux-arm64.tar.gz"
      sha256 "00b296cb83d23caa13cbcc627196af95cd840ae7ecf82dd0bedf7f0b66574223"
    end
    on_intel do
      url "https://github.com/yongjohnlee80/autodoc/releases/download/v0.1.20/autodoc-v0.1.20-linux-amd64.tar.gz"
      sha256 "c9509c105d58b580c11d480970d968e5b9c6f4ce6c8b35736f8bb8cdb9ad7f94"
    end
  end

  def install
    os = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "autodoc-v#{version}-#{os}-#{arch}" => "autodoc"
  end

  test do
    assert_match "autodoc v#{version}", shell_output("#{bin}/autodoc --version")
  end
end
