# typed: false
# frozen_string_literal: true

# Generated by scripts/update-formula.sh from the v0.4.7 release. Do not edit by hand.
class Autodb < Formula
  desc "Security-first SQL editor and PostgreSQL-wire gate for production databases"
  homepage "https://github.com/yongjohnlee80/autodb"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/yongjohnlee80/autodb/releases/download/v0.4.7/autodb-v0.4.7-darwin-arm64.tar.gz"
      sha256 "e416d040cd49563c05ec74921c2d975a320840f8bcb5109946410b5375c199fc"
    end
    on_intel do
      url "https://github.com/yongjohnlee80/autodb/releases/download/v0.4.7/autodb-v0.4.7-darwin-amd64.tar.gz"
      sha256 "bd057ed6a6bc54c7433fd461399ef9485f1d1d99568b8423b943115c0ed88446"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yongjohnlee80/autodb/releases/download/v0.4.7/autodb-v0.4.7-linux-arm64.tar.gz"
      sha256 "7d964e3bbf60de77b0da25a7b5c738934687e46d40dfea4ab13bdfae13cb3556"
    end
    on_intel do
      url "https://github.com/yongjohnlee80/autodb/releases/download/v0.4.7/autodb-v0.4.7-linux-amd64.tar.gz"
      sha256 "0674837e0e90dead02f2934f7b51697f453edcee7b4b496f0f1ceeb541d27e5d"
    end
  end

  def install
    os = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "autodb-v#{version}-#{os}-#{arch}" => "autodb"
  end

  test do
    assert_match "autodb v#{version}", shell_output("#{bin}/autodb --version")
  end
end
