# typed: false
# frozen_string_literal: true

# Generated by scripts/update-formula.sh from the v0.1.9 release. Do not edit by hand.
class Autodoc < Formula
  desc "Index, search and edit a tree of Markdown notes from a TUI or an RPC API"
  homepage "https://github.com/yongjohnlee80/autodoc"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/yongjohnlee80/autodoc/releases/download/v0.1.9/autodoc-v0.1.9-darwin-arm64.tar.gz"
      sha256 "c8f30a375e68650c7cbb42a47128a528ae0168eeef2934b2d14b4a0a83ee3020"
    end
    on_intel do
      url "https://github.com/yongjohnlee80/autodoc/releases/download/v0.1.9/autodoc-v0.1.9-darwin-amd64.tar.gz"
      sha256 "7e8eab541728f0db909b699dd05f26ffe98b6c6392288f1f7a321121c5ec2ffd"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yongjohnlee80/autodoc/releases/download/v0.1.9/autodoc-v0.1.9-linux-arm64.tar.gz"
      sha256 "9ce7720709687f7490a5ff1f62146a42d6a5f119c7670c53edc4fd2a13ad3f09"
    end
    on_intel do
      url "https://github.com/yongjohnlee80/autodoc/releases/download/v0.1.9/autodoc-v0.1.9-linux-amd64.tar.gz"
      sha256 "add965bd8069a9141e3d323a5e40706cca19ed1b1a3007d99d40e06a341d6a00"
    end
  end

  def install
    os = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "autodoc-v#{version}-#{os}-#{arch}" => "autodoc"
  end

  test do
    assert_match "autodoc v#{version}", shell_output("#{bin}/autodoc --version")
  end
end
