# typed: false
# frozen_string_literal: true

# Generated by scripts/update-formula.sh from the v0.4.4 release. Do not edit by hand.
class Autodb < Formula
  desc "Security-first SQL editor and PostgreSQL-wire gate for production databases"
  homepage "https://github.com/yongjohnlee80/autodb"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/yongjohnlee80/autodb/releases/download/v0.4.4/autodb-v0.4.4-darwin-arm64.tar.gz"
      sha256 "c1c0b8a92f86785240e38daf1e9fc340a031986b78aa95554aa134a548430c5f"
    end
    on_intel do
      url "https://github.com/yongjohnlee80/autodb/releases/download/v0.4.4/autodb-v0.4.4-darwin-amd64.tar.gz"
      sha256 "f46a2a322f22abd5022d3a84ce45527bee338012524ed64d615c203823f6be53"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yongjohnlee80/autodb/releases/download/v0.4.4/autodb-v0.4.4-linux-arm64.tar.gz"
      sha256 "8503eb2929680f975e0cf86c5e1dbec957645db666fd47f683df7d0667686223"
    end
    on_intel do
      url "https://github.com/yongjohnlee80/autodb/releases/download/v0.4.4/autodb-v0.4.4-linux-amd64.tar.gz"
      sha256 "7ca03e6b373733176a5dbe8d6043b72a712d2060154c62c27b29689da8bfdea7"
    end
  end

  def install
    os = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "autodb-v#{version}-#{os}-#{arch}" => "autodb"
  end

  test do
    assert_match "autodb v#{version}", shell_output("#{bin}/autodb --version")
  end
end
