# typed: false
# frozen_string_literal: true

# Generated by scripts/update-formula.sh from the v0.4.8 release. Do not edit by hand.
class Autodb < Formula
  desc "Security-first SQL editor and PostgreSQL-wire gate for production databases"
  homepage "https://github.com/yongjohnlee80/autodb"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/yongjohnlee80/autodb/releases/download/v0.4.8/autodb-v0.4.8-darwin-arm64.tar.gz"
      sha256 "799017b06894ffe607713725b5e8fd7aee547bb467d7323284697fa707c737a2"
    end
    on_intel do
      url "https://github.com/yongjohnlee80/autodb/releases/download/v0.4.8/autodb-v0.4.8-darwin-amd64.tar.gz"
      sha256 "1eaf45fdd664122caf329d65a70f8e1c84c1abf28ab556d657a1267bc753aed8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yongjohnlee80/autodb/releases/download/v0.4.8/autodb-v0.4.8-linux-arm64.tar.gz"
      sha256 "7ceacbb82d5846990d89af59ede79e6b6456845cbc7a02b490a5ceb913484759"
    end
    on_intel do
      url "https://github.com/yongjohnlee80/autodb/releases/download/v0.4.8/autodb-v0.4.8-linux-amd64.tar.gz"
      sha256 "e237edca5b6892bce3b3bf2a9913db685b742b2f666049a4810c07c7e57de647"
    end
  end

  def install
    os = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "autodb-v#{version}-#{os}-#{arch}" => "autodb"
  end

  test do
    assert_match "autodb v#{version}", shell_output("#{bin}/autodb --version")
  end
end
