# typed: false
# frozen_string_literal: true

# Generated by scripts/update-editor.sh from the v0.1.35 release. Do not edit by hand.
class AutodocEditor < Formula
  desc "Native Markdown editor and search UI for AutoDoc"
  homepage "https://github.com/yongjohnlee80/autodoc"
  license "Apache-2.0"
  depends_on :linux

  on_arm do
    url "https://github.com/yongjohnlee80/autodoc/releases/download/v0.1.35/autodoc-editor-v0.1.35-linux-arm64.tar.gz"
    sha256 "682d5d73eb1648a39b4851e862f83351a56c7bc224b1c04d72e1c3b0841cd172"
  end
  on_intel do
    url "https://github.com/yongjohnlee80/autodoc/releases/download/v0.1.35/autodoc-editor-v0.1.35-linux-amd64.tar.gz"
    sha256 "085685eaa5dde72c55ff9c0266af5b4aa6740eb5ddd75f9982e2aa5c306b3b3b"
  end

  def install
    bin.install "autodoc-editor"
    inreplace "autodoc-editor.desktop", "Exec=autodoc-editor", "Exec=#{opt_bin}/autodoc-editor"
    inreplace "autodoc-editor.desktop", "TryExec=autodoc-editor", "TryExec=#{opt_bin}/autodoc-editor"
    (share/"applications").install "autodoc-editor.desktop"
  end

  def caveats
    <<~EOS
      To show AutoDoc Editor in your graphical launcher, install its desktop entry:
        install -Dm644 "#{share}/applications/autodoc-editor.desktop" ~/.local/share/applications/autodoc-editor.desktop
    EOS
  end

  test do
    assert_match "autodoc v#{version}", shell_output("#{bin}/autodoc-editor --version")
  end
end
