# typed: false
# frozen_string_literal: true

# Generated by scripts/update-formula.sh from the v0.1.14 release. Do not edit by hand.
class Autodoc < Formula
  desc "Index, search and edit a tree of Markdown notes from a TUI or an RPC API"
  homepage "https://github.com/yongjohnlee80/autodoc"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/yongjohnlee80/autodoc/releases/download/v0.1.14/autodoc-v0.1.14-darwin-arm64.tar.gz"
      sha256 "5ffdea7d9a3b2b4d80f61bd4ed7c85741f05d0ca7e2a20b160d447ddcc279ff7"
    end
    on_intel do
      url "https://github.com/yongjohnlee80/autodoc/releases/download/v0.1.14/autodoc-v0.1.14-darwin-amd64.tar.gz"
      sha256 "fdd4b2d79f66c23c46c11cc26e755db08c6cd66f882fec2bea99338a43863a4b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yongjohnlee80/autodoc/releases/download/v0.1.14/autodoc-v0.1.14-linux-arm64.tar.gz"
      sha256 "44955aef62cccdc52a7b421213f6af34e45f6d8b56a0618699c3da0d2b60b750"
    end
    on_intel do
      url "https://github.com/yongjohnlee80/autodoc/releases/download/v0.1.14/autodoc-v0.1.14-linux-amd64.tar.gz"
      sha256 "807ecb12a4ed9350b900a29014cd44e6773ab9c43e2b386ad3fac5636ab5de2e"
    end
  end

  def install
    os = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "autodoc-v#{version}-#{os}-#{arch}" => "autodoc"
  end

  test do
    assert_match "autodoc v#{version}", shell_output("#{bin}/autodoc --version")
  end
end
