#!/bin/sh
set -eu

cd "$(dirname "$0")/.."
tag=${1:-}
if [ -z "$tag" ]; then
  tag=$(curl -fsSL https://api.github.com/repos/yongjohnlee80/autodoc/releases/latest |
    sed -n 's/^  "tag_name": "\(v[0-9][^"]*\)".*/\1/p')
fi
case "$tag" in
  v[0-9]*.[0-9]*.[0-9]*) ;;
  *) echo "error: not a release tag: '$tag'" >&2; exit 1 ;;
esac

asset="autodoc-editor-$tag-darwin-arm64.tar.gz"
base="https://github.com/yongjohnlee80/autodoc/releases/download/$tag"
if status=$(curl -sSL -o /dev/null -w '%{http_code}' "$base/$asset.sha256"); then
  case "$status" in
    200) ;;
    404) echo "$tag has no editor packages yet; leaving the editor tap unchanged"; exit 0 ;;
    *) echo "error: editor asset returned HTTP $status" >&2; exit 1 ;;
  esac
else
  echo "error: could not check the editor assets for $tag" >&2
  exit 1
fi

sha() {
  asset="autodoc-editor-$tag-$1.tar.gz"
  line=$(curl -fsSL "$base/$asset.sha256")
  sum=${line%% *}
  case "$sum" in
    *[!0-9a-f]*|'') echo "error: bad checksum for $asset" >&2; exit 1 ;;
  esac
  [ "${#sum}" -eq 64 ] || { echo "error: bad checksum for $asset" >&2; exit 1; }
  printf '%s' "$sum"
}

darwin_arm64=$(sha darwin-arm64)
darwin_amd64=$(sha darwin-amd64)
linux_arm64=$(sha linux-arm64)
linux_amd64=$(sha linux-amd64)
version=${tag#v}
mkdir -p Casks

cat > Casks/autodoc-editor.rb <<RUBY
# typed: false
# frozen_string_literal: true

# Generated by scripts/update-editor.sh from the $tag release. Do not edit by hand.
cask "autodoc-editor" do
  version "$version"

  on_arm do
    url "$base/autodoc-editor-$tag-darwin-arm64.tar.gz"
    sha256 "$darwin_arm64"
  end
  on_intel do
    url "$base/autodoc-editor-$tag-darwin-amd64.tar.gz"
    sha256 "$darwin_amd64"
  end

  name "AutoDoc Editor"
  desc "Native Markdown editor and search UI for AutoDoc"
  homepage "https://github.com/yongjohnlee80/autodoc"
  depends_on macos: :tahoe

  app "AutoDoc Editor.app"
  binary "#{appdir}/AutoDoc Editor.app/Contents/MacOS/autodoc-editor"
end
RUBY

cat > Formula/autodoc-editor.rb <<RUBY
# typed: false
# frozen_string_literal: true

# Generated by scripts/update-editor.sh from the $tag release. Do not edit by hand.
class AutodocEditor < Formula
  desc "Native Markdown editor and search UI for AutoDoc"
  homepage "https://github.com/yongjohnlee80/autodoc"
  license "Apache-2.0"
  depends_on :linux

  on_arm do
    url "$base/autodoc-editor-$tag-linux-arm64.tar.gz"
    sha256 "$linux_arm64"
  end
  on_intel do
    url "$base/autodoc-editor-$tag-linux-amd64.tar.gz"
    sha256 "$linux_amd64"
  end

  def install
    bin.install "autodoc-editor"
    inreplace "autodoc-editor.desktop", "Exec=autodoc-editor", "Exec=#{opt_bin}/autodoc-editor"
    (share/"applications").install "autodoc-editor.desktop"
  end

  def caveats
    <<~EOS
      To show AutoDoc Editor in your graphical launcher, install its desktop entry:
        install -Dm644 "#{share}/applications/autodoc-editor.desktop" ~/.local/share/applications/autodoc-editor.desktop
    EOS
  end

  test do
    assert_match "autodoc v#{version}", shell_output("#{bin}/autodoc-editor --version")
    desktop = (share/"applications/autodoc-editor.desktop").read
    assert_match "Exec=#{opt_bin}/autodoc-editor", desktop
    assert_match "TryExec=#{opt_bin}/autodoc-editor", desktop
  end
end
RUBY

echo "Casks/autodoc-editor.rb and Formula/autodoc-editor.rb -> $tag"
