#!/bin/sh
# Render Formula/autodb.rb for an autodb release.
#
#   scripts/update-formula.sh            # the newest release
#   scripts/update-formula.sh v0.4.1     # a specific tag
#
# It reads only public release assets: each archive's published .sha256 file.
# Nothing is built or re-hashed here, so the formula pins exactly what the
# release workflow published.
set -eu

REPO="yongjohnlee80/autodb"
cd "$(dirname "$0")/.."

tag="${1:-}"
if [ -z "$tag" ]; then
  tag="$(curl -fsSL "https://api.github.com/repos/$REPO/releases/latest" \
    | sed -n 's/^  "tag_name": "\(v[0-9][^"]*\)".*/\1/p')"
fi
case "$tag" in
  v[0-9]*.[0-9]*.[0-9]*) ;;
  *) echo "error: not a release tag: '$tag'" >&2; exit 1 ;;
esac
version="${tag#v}"

sha() {
  asset="autodb-$tag-$1.tar.gz"
  line="$(curl -fsSL "https://github.com/$REPO/releases/download/$tag/$asset.sha256")"
  sum="${line%% *}"
  case "$sum" in
    [0-9a-f][0-9a-f][0-9a-f][0-9a-f]*) ;;
    *) echo "error: no checksum for $asset" >&2; exit 1 ;;
  esac
  [ "${#sum}" -eq 64 ] || { echo "error: bad checksum for $asset: $sum" >&2; exit 1; }
  printf '%s' "$sum"
}

darwin_arm64="$(sha darwin-arm64)"
darwin_amd64="$(sha darwin-amd64)"
linux_arm64="$(sha linux-arm64)"
linux_amd64="$(sha linux-amd64)"

cat > Formula/autodb.rb <<RUBY
# typed: false
# frozen_string_literal: true

# Generated by scripts/update-formula.sh from the $tag release. Do not edit by hand.
class Autodb < Formula
  desc "Security-first SQL editor and PostgreSQL-wire gate for production databases"
  homepage "https://github.com/$REPO"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/$REPO/releases/download/$tag/autodb-$tag-darwin-arm64.tar.gz"
      sha256 "$darwin_arm64"
    end
    on_intel do
      url "https://github.com/$REPO/releases/download/$tag/autodb-$tag-darwin-amd64.tar.gz"
      sha256 "$darwin_amd64"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/$REPO/releases/download/$tag/autodb-$tag-linux-arm64.tar.gz"
      sha256 "$linux_arm64"
    end
    on_intel do
      url "https://github.com/$REPO/releases/download/$tag/autodb-$tag-linux-amd64.tar.gz"
      sha256 "$linux_amd64"
    end
  end

  def install
    os = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "autodb-v#{version}-#{os}-#{arch}" => "autodb"
  end

  test do
    assert_match "autodb v#{version}", shell_output("#{bin}/autodb --version")
  end
end
RUBY

echo "Formula/autodb.rb -> $tag"
